import type { ExperienceItemType } from "@/features/home/work-experience";

export const WORK_EXPERIENCE: ExperienceItemType[] = [
  {
    id: "1",
    companyName: "Studio Twenty Sdn Bhd",
    companyLogo: "/work/studio20my_logo.jpg",
    isCurrentEmployer: true,
    positions: [
      {
        id: "1-1",
        title: "Junior Full Stack Developer/ Mobile Developer",
        employmentPeriod: "Janurary 2024 - Present",
        employmentType: "Full-time",
        description: `I contributed and sometimes led development of multiple production-grade platforms across analytics, enterprise, government, and nonprofit domains—including an AI-powered social media analytics dashboard that increased website traffic by 30%, an enterprise dashboard for the Singapore Business Federation to manage surveys and quantify business readiness across six national indices, cross-platform mobile apps and a centralized dashboard for a Malaysian Government–sponsored education system, six high-traffic sports websites and a custom CMS for the Football Association of Singapore, and an end-to-end sales, delivery, and tracking platform with Android apps supporting family-run farms in underprivileged regions through Care Channel International.`,
        icon: "code",
        skills: [
          "Next.js",
          "React.js",
          "Typescript",
          "Nest Js",
          "Tailwind CSS",
          "Vite",
          "PostgresSQL",
          "Kotlin",
          "HTML",
          "CSS",
        ],
        isExpanded: true,
      },
      {
        id: "1-2",
        title: "Entry level Frontend Developer",
        employmentPeriod: "April 2024 - December 2024",
        employmentType: "Full-time",
        description: `When I joined the studio, my first task was to integrate the sport radar api to fetch live sports fixtures and matches for the previous Singapore Premier League wordpress website, which is the first time, I had to learn wordpress development and plugins. Then after that, was tasked to do the same with Singapore Youth League website, and create pages for the Accrediation System page and clubs. During this year, I also helped out with the frontend developer of financial dashboard and voucher sale, and distribution platform as the main React developer.`,
        icon: "code",
        skills: [
          "Wordpress",
          "PHP",
          "Javascript",
          "Alphine js",
          "React.js",
          "Tailwind CSS",
          "Vite",
          "HTML",
          "CSS",
        ],
        isExpanded: true,
      },
    ],
  },
  {
    id: "2",
    companyName: "Master Material Logistics",
    companyLogo: "/work/master_material_suppliers_logo.jpg",
    isCurrentEmployer: false,
    positions: [
      {
        id: "2-1",
        title: "System Engineer & Backend Developer",
        employmentPeriod: "July 2025 - October 2025",
        employmentType: "Freelance",
        description: `Commissioned to build a logistics platform that can generate quotations documents for customers, track customers' order processing and shippment across multiple countries and companies, along with automating workflows for efficient operations. Primarily responsible for designing the system architecture, site hosting, choosing tech stacks, database design and is a primary backend developer.`,
        icon: "code",
        skills: ["Database Design", "Nest JS", "Typescript", "Cron Job"],
        isExpanded: false,
      },
    ],
  },
  {
    id: "3",
    companyName: "Lionmark Pte Ltd",
    companyLogo: "/work/lionmark.png",
    isCurrentEmployer: false,
    positions: [
      {
        id: "3-1",
        title: "Full Stack Developer",
        employmentPeriod: "November 2024 - Present",
        employmentType: "Freelance",
        description: `Lionmark is a newly registered training provider for the skill future programme run by the Singapore Government, and to help out with the scaling of their class room training they wanted to created a Training Management System (TMS). This will integrated with the skill future TPGateway to allow creation and management of their classroom schedules, enrollments, attendances with Singpass, and assessment results in addition to automating email and whatsapp sending to the trainee that registered their courses. As a solo developer, I am responsible for creating the system architecture, site hosting, choosing tech stacks, database design, as well as building the system itself.`,
        icon: "code",
        skills: [
          "Next.js",
          "Elysia.js",
          "Typescript",
          "React",
          "Tailwind CSS",
          "MySQL",
          "React",
          "HTML",
          "CSS",
        ],
        isExpanded: false,
      },
    ],
  },
];
